version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: lab6-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lab6
      POSTGRES_USER: lab6
      POSTGRES_PASSWORD: lab6
    ports:
      - "5432:5432"
    volumes:
      - pgdata_lab5:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lab6 -d lab6" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_lab5:
    driver: local
